Repository AbhishekChamp879/Mind_Care, pull requests merged in 2025-10, with the labels that each got.

#4 Added Quick Mood Check-ins: One-Tap Wellness Tracking feature!!!
  src/App.tsx
  src/components/dashboard/FloatingMoodButton.tsx
  src/components/dashboard/MoodAnalytics.tsx
  src/components/dashboard/MoodWidgets.tsx
  src/components/dashboard/QuickMoodCheckIn.tsx
  src/components/dashboard/QuickMoodHeader.tsx
  src/components/dashboard/QuickMoodShowcase.tsx
  src/components/layout/Header.tsx
  src/pages/StudentDashboard.tsx
Labels: enhancement, good first issues, hacktoberfest-accepted, hacktoberfest

#5 Added comprehensive Session Feedback & Rating System for Mental Health Platform!
  src/App.tsx
  src/components/feedback/FeedbackForm.tsx
  src/components/feedback/RatingComponent.tsx
  src/pages/FeedbackDemo.tsx
  src/types/feedback.ts
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#6 feat: Real-time Guided Meditation & Breathing Exercises
  src/components/meditation/AmbientSoundPlayer.tsx
  src/components/meditation/BreathingAnimation.tsx
  src/components/meditation/MeditationDashboard.tsx
  src/components/meditation/MeditationTimer.tsx
  src/components/meditation/MindfulnessProgressTracker.tsx
  src/pages/MeditationDemo.tsx
  src/types/meditation.ts
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#9 UI Enhancement: Typography and Component Refinements
  bun.lockb
  src/App.tsx
  src/components/dashboard/FloatingMoodButton.tsx
  src/components/dashboard/MoodAnalytics.tsx
  src/components/dashboard/MoodWidgets.tsx
  src/components/dashboard/QuickMoodCheckIn.tsx
  src/components/dashboard/QuickMoodHeader.tsx
  src/components/dashboard/QuickMoodShowcase.tsx
  src/components/feedback/FeedbackForm.tsx
  src/components/feedback/RatingComponent.tsx
  src/components/layout/Header.tsx
  src/components/meditation/AmbientSoundPlayer.tsx
  src/components/meditation/BreathingAnimation.tsx
  src/components/meditation/MeditationDashboard.tsx
  src/components/meditation/MeditationTimer.tsx
  src/components/meditation/MindfulnessProgressTracker.tsx
  src/components/peer-matching/MentorMatchingSystem.tsx
  src/components/peer-matching/PeerBuddyMatching.tsx
  src/components/peer-matching/PeerMatchingDashboard.tsx
  src/components/peer-matching/PeerMatchingDemo.tsx
  src/components/peer-matching/RealTimeConnectionSystem.tsx
  src/components/peer-matching/StudyGroupSystem.tsx
  src/components/settings/EnhancedThemeSettings.tsx
  src/components/ui/reading-mode-button.tsx
  src/components/ui/theme-toggle.tsx
  src/contexts/ThemeContext.tsx
  src/index.css
  src/pages/FeedbackDemo.tsx
  src/pages/Index.tsx
  src/pages/MeditationDemo.tsx
  src/pages/Resources.tsx
  src/pages/StudentDashboard.tsx
  src/styles/enhanced-theme.css
  src/types/feedback.ts
  src/types/meditation.ts
  src/types/peerMatching.ts
  src/types/theme.ts
  tailwind.config.ts
Labels: good first issues, hacktoberfest-accepted, hacktoberfest, ui/ux

#8 corrected clone link in README.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#16 Add: Footer & Favicon closes issue #13
  index.html
  public/logo.png
  src/pages/Index.tsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, ui/ux

#28 FEAT: Added lofi background music player
  public/music/lofi-study.mp3
  src/App.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/music/BackgroundMusicPlayer.tsx
  src/contexts/MusicContext.tsx
  src/types/music.ts
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#26 Doc: Add pull request template for better contribution guidelines
  .github/pull_request_template.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#33 CI implementation
  .github/workflows/build-check.yml
  .github/workflows/format.yml
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
Labels: good first issues, hacktoberfest-accepted, hacktoberfest, dependencies

#43 Added footer to the website
  src/components/layout/Footer.tsx
  src/components/layout/Layout.tsx
  src/pages/About.tsx
  src/pages/ContactUs.tsx
  src/pages/Index.tsx
  src/pages/Login.tsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, ui/ux

#58 Refactor Navigation Architecture — Ensure Global Mode Consistency & Accurate Page Access
  package-lock.json
  package.json
  src/components/layout/Header.tsx
  src/pages/About.tsx
  src/pages/ContactUs.tsx
  src/pages/MentalHealthBlog.tsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, ui/ux

#61 Improved Text Visibility of Blog page (Light Mode) & added relevant images for blogs
  src/components/layout/Layout.tsx
  src/pages/MentalHealthBlog.tsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, ui/ux

#72 feat: Hide footer on login page
  src/App.tsx
  src/pages/Login.tsx
Labels: bug, enhancement, hacktoberfest-accepted, hacktoberfest
